export enum StatusCodeString {
  BAD_REQUEST = "BAD_REQUEST",
  NOT_FOUND = "NOT_FOUND",
  PRECONDITION_FAILED = "PRECONDITION_FAILED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  BAD_GATEWAY = "BAD_GATEWAY",
}